### ISSUE TITLE
The plugin only works on Jenkinsfile in $PWD

### ISSUE THREAD

**Issue by Ashymad** [burnettk/vim-jenkins#3]
The check for filename doesn't consider that it can be opened from a different dir. e.g. `nvim Jenkinsfile` works but `nvim ../Jenkinsfile` doesn\t. Besides that great plugin!

**Comment by burnettk** [comment]
@Ashymad glad you're enjoying it. this issue is fixed now. please update. also, completely unrelated, we just released some dotfiles. If you have a spare computer and want to play around, that would be amazing: https://github.com/no-term-limits/no-term-limits

**Comment by Ashymad** [comment]
Thanks!
